#! /bin/bash

handle_error() {
  #Add additional error functions later if required
  echo "could not create data directory";
}

trap 'handle_error' ERR

if [ ! -d "/var/lib/cultiva/captures" ]; then
  mkdir -p /var/lib/cultiva/captures;
fi
if [ ! -d "/etc/cultiva" ]; then
  mkdir /etc/cultiva;
fi